### ISSUE TITLE
Failed to install CLI

### ISSUE THREAD

**Issue by Tutmanichtun** [Pinoccio/client-node-pinoccio#29]
Hi there,
just tried to install the CLI on my Laptop an got this Output:
`gregor@Loetplatz-PC:~$ sudo npm install -g pinoccio
/usr/local/bin/pinoccio -> /usr/local/lib/node_modules/pinoccio/bin/pinoccio.js

> reset-usb@0.0.1 install /usr/local/lib/node_modules/pinoccio/node_modules/reset-usb
> node-gyp rebuild

make: Verzeichnis „/usr/local/lib/node_modules/pinoccio/node_modules/reset-usb/build“ wird betreten
  CXX(target) Release/obj.target/resetusb/src/resetusb.o
In file included from ../src/resetusb.cpp:10:0:
../../nan/nan.h:120:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../../nan/nan.h:115:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../../nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../../nan/nan.h:207:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                              ^
In file included from /usr/include/nodejs/src/node.h:42:0,
                 from ../../nan/nan.h:23,
                 from ../src/resetusb.cpp:10:
/usr/include/nodejs/deps/v8/include/v8.h:4675:27: note: candidate: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/usr/include/nodejs/deps/v8/include/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/resetusb.cpp:10:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:289:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
   NanNew<v8::StringObject, v8::Handle<v8::String> >(
   ^
../../nan/nan.h:282:3: note: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
   NanNew<v8::StringObject, v8::Local<v8::String> >(
   ^
../../nan/nan.h:307:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:301:36: note: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:319:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:313:36: note: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../../nan/nan.h:778:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:778:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:782:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:782:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:789:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:24:0,
                 from ../src/resetusb.cpp:10:
/usr/include/nodejs/src/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/resetusb.cpp:10:0:
../../nan/nan.h:789:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:24:0,
                 from ../src/resetusb.cpp:10:
/usr/include/nodejs/src/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/include/nodejs/src/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/resetusb.cpp:10:0:
../../nan/nan.h:789:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:793:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:800:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
resetusb.target.mk:92: die Regel für Ziel „Release/obj.target/resetusb/src/resetusb.o“ scheiterte
make: *** [Release/obj.target/resetusb/src/resetusb.o] Fehler 1
make: Verzeichnis „/usr/local/lib/node_modules/pinoccio/node_modules/reset-usb/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pinoccio/node_modules/reset-usb
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:reset-usb@0.0.1 reset-usb@0.0.1 install: `node-gyp rebuild`
npm WARN install:reset-usb@0.0.1 Exit status 1

> serialport@1.5.0 install /usr/local/lib/node_modules/pinoccio/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-serialport.s3.amazonaws.com/serialport/v1.5.0/Release/node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@1.5.0 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/gregor/.node-gyp/4.2.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/pinoccio/node_modules/serialport/.node-gyp"
make: Verzeichnis „/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build“ wird betreten
make: *** Keine Regel vorhanden, um das Ziel „../.node-gyp/4.2.6/include/node/common.gypi“, 
  benötigt von „Makefile“, zu erstellen.  Schluss.
make: Verzeichnis „/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/share/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build/serialport/v1.5.0/Release/node-v46-linux-x64/serialport.node" "--module_name=serialport" "--module_path=/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build/serialport/v1.5.0/Release/node-v46-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/pinoccio/node_modules/serialport
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/share/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build/serialport/v1.5.0/Release/node-v46-linux-x64/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build/serialport/v1.5.0/Release/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pinoccio/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-22-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/pinoccio/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/pinoccio/node_modules/serialport
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/share/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build/serialport/v1.5.0/Release/node-v46-linux-x64/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/pinoccio/node_modules/serialport/build/serialport/v1.5.0/Release/node-v46-linux-x64' (1)
/usr/local/lib
└── (empty)

npm WARN In serialport@1.5.0 replacing bundled version of node-pre-gyp with node-pre-gyp@0.6.28
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pinoccio"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.5.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gregor/npm-debug.log
npm ERR! code 1
gregor@Loetplatz-PC:~$ `

System: lubuntu 16.04
Node-Version: 4.2.6
NPM-Version: 3.5.2

Background is this Thread: http://discuss.pinocc.io/t/problems-with-the-hq/538
Uploaded NPM-Logfile: [npm-debug.log.txt](https://github.com/Pinoccio/client-node-pinoccio/files/264466/npm-debug.log.txt) (added additional .txt-Ending to make it Github-compatible.)

**Comment by soldair** [comment]
i have a moment to take a look. thanks for proper debug info

the cli hasnt been updated for newer nodes yet. reset usb is an optional dep so its ok that it fails and wont fail the install if it does.

**Comment by dvanduzer** [comment]
What happened with #27 for that matter? That branch fixes this issue, but the test suite was still failing.

**Comment by soldair** [comment]
oh interesting i have it updated on my local. ill push a branch for review

**Comment by soldair** [comment]
i dont know the current status of hq so there are a number of things that wont work without using https://github.com/soldair/pinoccio-server and finishing api compat

**Comment by soldair** [comment]
https://github.com/Pinoccio/client-node-pinoccio/pull/30

bumps the version of serialport to one that works with node 4.x. we'll probably have to update again because i tested this a while back.

reset usb blows up but agian as an optional dep it doesn't cause the install to fail.

**Comment by dvanduzer** [comment]
HQ should remain running indefinitely (although the URL may change at some point). Only one of these checks is failing, and I can't figure out what it's trying to test.

**Comment by soldair** [comment]
@dvanduzer are you in slack? i forgot the url.

published 0.1.40 of pinoccio on npm. should compile just fine on >=4.x

**Comment by soldair** [comment]
@Tutmanichtun let me know if it works for you. maybe reopen if it doesnt.
